spring:
  application:
    name: dw

  datasource:
    url: jdbc:postgresql://localhost:5432/dw
    username: pg
    password: pg
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

